name: Daily Equation Update

on:
  schedule:
    - cron: "0 0 * * *" # Se lance toutes les nuits à minuit (UTC)
  workflow_dispatch: # Permet de le lancer à la main pour tester

jobs:
  build:
    runs-on: ubuntu-latest

    # --- LA LIGNE MAGIQUE EST ICI ---
    permissions:
      contents: write
    # --------------------------------

    steps:
      - name: Récupérer le code du projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Lancer ton script
        run: |
          python main.py

      - name: Enregistrer les changements
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Mise à jour de l'équation du jour" || echo "Pas de changement"
          git push
